DROP TABLE artists;
DROP TABLE albums;
DROP TABLE

CREATE TABLE artists(
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
);

CREATE TABLE albums(
is SERIAL8 PRIMARY KEY,
title VARCHAR(255) NOT NULL,
genre VARCHAR(255) NOT NULL,
stock INT4
);
