DROP TABLE artists;
DROP TABLE albums;

CREATE TABLE artists(
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  origin VARCHAR(255) NOT NULL
);

CREATE TABLE albums(
id SERIAL8 PRIMARY KEY,
title VARCHAR(255) NOT NULL,
genre VARCHAR(255) NOT NULL,
stock INT4,
artist_id INT4 REFERENCES artists(id) ON DELETE CASCADE
);
